<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 5,
                'category_id' => 1,
                'vendor_id' => 1,
                'name' => 'Táo Envy Mỹ',
                'description' => "- Xuất xứ: Mỹ\r\n\r\n- Chất lượng: Nhập khẩu\r\n\r\n- Khối lượng: 600G/2 Trái\r\n\r\n- Đặc điểm:\r\n\r\nThơm - ngọt - mọng nước - giòn tan khi thưởng thức.\r\nSize càng nhỏ thì cỡ táo càng to.\r\nLà dòng táo ưa thích của đại đa số gia đình!\r\n- Lợi ích:\r\n\r\nHỗ trợ sức khỏe tim mạch: Táo Envy chứa hàm lượng kali cao, giúp điều hòa huyết áp, giảm nguy cơ mắc các bệnh tim mạch.\r\nTăng cường hệ miễn dịch: Táo Envy giàu vitamin C, giúp tăng cường hệ miễn dịch, chống lại các bệnh cảm cúm, ho, sổ mũi.\r\nHỗ trợ hệ tiêu hóa: Táo Envy chứa nhiều chất xơ, giúp hỗ trợ hệ tiêu hóa, ngăn ngừa táo bón và các bệnh đường ruột.\r\nTốt cho da: Táo Envy chứa vitamin A và E, giúp chống oxy hóa, bảo vệ da khỏi tác hại của ánh nắng mặt trời và làm đẹp da.\r\nGiúp giảm cân: Táo Envy ít calo, nhiều chất xơ, giúp tạo cảm giác no lâu, hỗ trợ giảm cân hiệu quả.\r\n- Hướng dẫn sử dụng:\r\n\r\nRửa nhẹ nhàng trái táo. Sau đó cắt đôi trái táo và loại bỏ phần hạt bên trong.\r\nBảo quản trong ngăn mát tủ lạnh. Táo giữ được độ tươi, độ giòn trong vòng 1-4 tuần. Sau thời gian này, táo sẽ ngọt hơn, độ giòn thấp hơn và táo trở nên xốp.\r\nCần tránh để táo với các thực phẩm có mùi khác như hành, tỏi, táo sẽ dễ nhiễm mùi.\r\nKhông rửa trước khi cho vào tủ lạnh.\r\n- Táo có thể được sử dụng để làm gì?\r\n\r\nSinh tố: táo kết hợp với các loại trái cây khác như chuối, dâu tây, sữa chua,... để tạo thành món sinh tố thơm ngon và đầy dinh dưỡng.\r\nSalad: Táo cắt nhỏ, trộn với các loại rau củ quả khác cùng với nước sốt yêu thích để tạo thành món salad thanh mát và đầy đủ dưỡng chất.\r\nNước ép: Táo ép lấy nước có thể uống trực tiếp hoặc pha thêm mật ong để tăng hương vị.\r\nBánh táo: Táo được sử dụng làm nhân cho bánh táo hoặc trang trí mặt bánh.\r\nMứt táo: Táo có thể được nấu thành mứt để ăn kèm với bánh mì hoặc sử dụng trong các món tráng miệng.",
                'images' => '["products/6635f05c93df4.webp", "products/6635f05cc1964.webp", "products/6635f05d031c2.webp"]',
                'unit' => 'kg',
                'quantity' => 7.40,
                'price' => 161400,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:44:34',
                'updated_at' => '2024-05-19 01:32:48',
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'vendor_id' => 1,
                'name' => 'Cherry đỏ Mỹ',
                'description' => "- Xuất xứ: Mỹ\r\n\r\n- Tiêu chuẩn chất lượng: Nhập khẩu\r\n\r\nĐặc điểm nổi bật:\r\n\r\nCherry đầu mùa tươi roi rói, màu đỏ đẹp mắt \r\nTrái cứng tương đối, vị ngọt thanh, chua rất dịu \r\nThông tin dinh dưỡng:\r\n\r\nQuả cherry rất tốt cho những người bị cao huyết áp, giúp bạn loại bỏ được mức độ cholesterol xấu trong cơ thể.\r\nĂn cherry thường xuyên giúp cải thiện tình trạng mất ngủ của bạn.\r\nCherry là thực phẩm tốt cho não bộ, tăng trí nhớ bởi chúng chứa các chất chống ôxy hóa anthocyanin.\r\nTrong loại trái cây này có chứa rất nhiều vitamin, đặc biệt là vitamin A. Các vitamin này không chỉ giúp tăng sức đề kháng mà còn rất tốt cho mắt.\r\nVị ngọt của cherry hoàn toàn tự nhiên, chỉ số đường tương đối thấp, đem đến công dụng tuyệt vời cho việc điều trị tiểu đường.\r\n- Hướng dẫn sử dụng:\r\n\r\nRửa nhẹ nhàng trái \r\n\r\nChỉ nên rửa một lượng vừa đủ ăn.\r\n\r\nCherry có thể ăn trực tiếp, làm nước ép, sinh tố, làm bánh\r\n\r\n- Cách lựa chọn:\r\nKhách hàng nên chọn những quả căng bóng, có màu đỏ đều, không bị dập nát, thối rữa.\r\n\r\nVới Farmers Market tiêu chí hàng đầu là sản phảm đạt chất lượng cao, nguồn gốc rõ ràng, mang đến trải nghiệm tốt nhất cho khách hàng. \r\n\r\n- Cách bảo quản: \r\n+ Bảo quản trong tủ lạnh:\r\n\r\nSau khi mua về, nhẹ nhàng nhặt bỏ những quả bị dập nát, thối rữa.\r\nCho cherry vào hộp kín hoặc túi nilon có đục lỗ.\r\nBảo quản cherry trong ngăn mát tủ lạnh.\r\nKiểm tra thường xuyên và loại bỏ những trái hư hỏng\r\nKhông nên rửa cherry trước khi bảo quản trong tủ lạnh vì sẽ khiến quả dễ bị thối rữa.\r\nNếu muốn bảo quản cherry lâu hơn, có thể đông lạnh cherry.\r\n+ Bảo quản ở nhiệt độ phòng:\r\n\r\nNếu bạn muốn ăn cherry ngay trong ngày, có thể bảo quản cherry ở nhiệt độ phòng.\r\nTuy nhiên, cherry sẽ chỉ tươi ngon trong vòng 1-2 ngày.\r\nNên đặt cherry ở nơi thoáng mát, tránh ánh nắng trực tiếp.\r\n- Những lưu ý khi thưởng thức cherry:\r\nNên rửa sạch cherry trước khi ăn để đảm bảo vệ sinh.\r\nNếu bạn có dị ứng với cherry hoặc bất kỳ loại trái cây nào khác, hãy tránh ăn cherry.\r\nTránh cho trẻ ăn cherry trước khi đi ngủ vì có thể gây khó tiêu.\r\n- Phụ nữ mang thai và trẻ em ăn cherry có được không?\r\n\r\nPhụ nữ mang thai nên ăn nho với lượng vừa phải, khoảng 100-150 gram mỗi ngày\r\n\r\nTrẻ em trên 1 tuổi có thể ăn cherry, cắt nho thành từng miếng nhỏ để trẻ dễ ăn và tránh nguy cơ nghẹn.\r\n\r\nCho trẻ ăn nho với lượng vừa phải, khoảng 50-100 gram mỗi ngày",
                'images' => '["products/6635ed3a42000.webp"]',
                'unit' => 'kg',
                'quantity' => 4.90,
                'price' => 89000,
                'discount' => 0.10,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:52:16',
                'updated_at' => '2024-05-18 16:53:10',
            ],
            [
                'id' => 7,
                'category_id' => 1,
                'vendor_id' => 6,
                'name' => 'Nho mẫu đơn Premium Hàn Quốc',
                'description' => "Nho mẫu đơn Premium Hàn Quốc (450G/Hộp)\r\n\r\nXuất xứ: Hàn Quốc\r\n\r\nTrọng lượng sản phẩm: 450G\r\nMô tả sản phẩm:\r\n\r\n- Đóng gói: 450G/Hộp\r\n\r\n- Trái to, dạng nho sữa trái mềm, ko giòn, độ ngọt vừa phải, thơm sữa thoang thoảng. \r\n\r\nHướng dẫn sử dụng:\r\n\r\n- Không nên rửa nho trước khi bảo quản trong ngăn mát tủ lạnh vì nếu rửa trước nho sẽ dễ bị hư, thối.\r\n\r\n- Chỉ nên rửa một lượng vừa đủ ăn.",
                'images' => '["products/662b5d77ce4f1.webp", "products/662b5d782d7c2.webp", "products/662b5d784a8bb.webp"]',
                'unit' => 'kg',
                'quantity' => 8.00,
                'price' => 399000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:53:28',
                'updated_at' => '2024-05-19 20:10:52',
            ],
            [
                'id' => 8,
                'category_id' => 2,
                'vendor_id' => 3,
                'name' => 'Bưởi da xanh',
                'description' => "Xuất xứ: Việt Nam\r\n\r\nTiêu chuẩn chất lượng: Trái cây sạch\r\n\r\nKhối lượng: 1Kg - 1,1Kg/Trái\r\n\r\nĐặc điểm nổi bật:\r\n\r\nBưởi là một loại thực phẩm vô cùng lành mạnh để đưa vào chế độ ăn uống.\r\nPhần ruột màu hồng trắng với các tép mọng nước vô cùng hấp dẫn. Trái có vị ngọt, bưởi hái xuống để càng lâu độ ngọt càng cao.",
                'images' => '["products/662b5dccc7303.webp", "products/662b5dcd61475.webp", "products/662b5dcd896a8.webp"]',
                'unit' => 'kg',
                'quantity' => 6.30,
                'price' => 89000,
                'discount' => 0.22,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:54:53',
                'updated_at' => '2024-05-19 20:13:36',
            ],
            [
                'id' => 9,
                'category_id' => 2,
                'vendor_id' => 3,
                'name' => 'Cam sành',
                'description' => "Xuất xứ: Việt Nam\r\n\r\nKhối lượng: 3 - 4 Trái/Kg\r\n\r\nĐặc Điểm:\r\n\r\nQuy trình chăm sóc tiên tiến\r\nDễ nhận dạng nhờ lớp vỏ dày, sần sùi, thường có màu xanh lục nhạt, khi chín có sắc cam.\r\nMúi thịt màu cam, có vị thơm đặc trưng, ngọt dịu.\r\nCam Sành có kích thước vừa phải, mọng nước, vỏ xanh xen chút vàng với múi màu cam đẹp mắt. Dùng làm nước ép cũng rất ngon",
                'images' => '["products/662b5f5ec3fdf.webp", "products/662b5f5ee34f3.webp", "products/662b5f5f183da.webp", "products/662b5f5f410c9.webp"]',
                'unit' => 'kg',
                'quantity' => 8.70,
                'price' => 27000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:56:14',
                'updated_at' => '2024-05-05 01:17:28',
            ],
            [
                'id' => 10,
                'category_id' => 1,
                'vendor_id' => 5,
                'name' => 'Cam vàng Ai Cập',
                'description' => "Cam vàng Ai Cập\r\n\r\nXuất xứ: Ai Cập\r\n\r\nTiêu chuẩn chất lượng: Nhập khẩu\r\n\r\nTrọng lượng: 1Kg tầm 4 - 5 trái\r\nĐặc điểm nổi bật: Trái to, mọng nước, KHÔNG HẠT, ngọt thơm, chua nhẹ không đáng kể\r\n\r\nHướng dẫn sử dụng:\r\n\r\nNhẹ nhàng rửa cam với nước sạch, sau đó dùng dao cắt thành những miếng vừa ăn.\r\nCam có thể được bảo quản ở nhiệt độ thường hoặc trong tủ lạnh. Nếu bảo quản trong tủ lạnh, nhiệt độ thích hợp nhất từ 7 - 10 độ C.\r\nNên bảo quản cam tự nhiên, không bỏ vào túi nhựa vì cam sẽ mau hư, dễ xuất hiện nấm mốc.\r\nKhông rửa trước khi cho vào tủ lạnh.\r\nLợi ích sức khỏe:\r\n\r\nTăng cường hệ miễn dịch\r\nHỗ trợ tiêu hóa\r\nTốt cho tim mạch\r\nGiúp đẹp da\r\nNgăn ngừa ung thư",
                'images' => '["products/662b5e6e81e2c.webp", "products/662b5e6f03220.webp", "products/662b5e6f2fc83.webp"]',
                'unit' => 'kg',
                'quantity' => 5.50,
                'price' => 99000,
                'discount' => 0.20,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:57:35',
                'updated_at' => '2024-05-17 23:48:13',
            ],
            [
                'id' => 11,
                'category_id' => 3,
                'vendor_id' => 4,
                'name' => 'Giỏ Trái Cây Tài Lộc - Phú Quý',
                'description' => "Vui lòng đặt trước 3 GIỜ, để quà tặng được chuẩn bị tốt nhất! \r\n\r\nGiỏ quà bao gồm:\r\n- Quýt nội địa Trung size M | 20 Trái\r\n- Khay hộp quà đỏ họa tiết vàng Farmers Market (34x25x10.8)\r\n- Túi giấy ngang Farmers Market\r\n- Bộ phụ kiện hoa + nơ đỏ + tem dán\r\n \r\n\r\n* Màu lưới bọc giỏ quà và nơ có thể thay đổi theo yêu cầu. Quý khách vui lòng ghi chú trong đơn hàng. \r\n\r\n* Do tính chất mùa vụ, trái cây và hoa có thể thay đổi với giá trị tương đương. \r\n\r\n* Cửa hàng sẽ liên hệ thông báo khi có sự thay đổi. \r\n\r\nLưu ý: Phí ship áp dụng cho 1 set quà, nếu quý khách đặt hơn 1 set quà phí ship sẽ được báo chính xác lại vào thời điểm giao hàng.",
                'images' => '["products/662b5ed68ae7b.webp", "products/662b5ed6e99e3.webp", "products/662b5ed723576.webp"]',
                'unit' => 'giỏ',
                'quantity' => 1.00,
                'price' => 396000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:59:19',
                'updated_at' => '2024-05-19 01:33:27',
            ],
            [
                'id' => 12,
                'category_id' => 3,
                'vendor_id' => 4,
                'name' => 'Giỏ Trái Cây Nhập Tông Hồng Hoạ Tiết Vàng',
                'description' => "Vui lòng đặt trước 3 GIỜ, để quà tặng được chuẩn bị tốt nhất! \r\n\r\nGiỏ quà bao gồm:\r\n- Táo Tessa Hà Lan (4 trái, khoảng 600g) \r\n- Quýt nội địa Trung | Size M (2 trái, khoảng 360g) \r\n- Táo xanh Granny Smith Mỹ | Size 90 - 100 (2 trái, khoảng 400g) \r\n- Dưa lưới TL3 (1 trái, khoảng 1,2 - 1,4kg) \r\n- Nho xanh Autumn Crisp Úc (300g) \r\n- Lê nâu nội địa Trung (1 trái, khoảng 450g) \r\n- Cam vàng nội địa Trung (5 trái, khoảng 1,2kg) \r\n- Khay quà hồng họa tiết vàng (34 x 25 x 10.8cm) \r\n- Túi vải xanh không dệt | Size M\r\n* Giá tiền có thể chênh lệch dựa trên khối lượng thực tế của sản phẩm và thời giá. \r\n\r\n* Trái cây có thể thay đổi do tính chất mùa vụ, sẽ được đổi bằng sản phẩm có giá trị tương đương. \r\n\r\n* Cửa hàng sẽ liên hệ thông báo khi có sự thay đổi. \r\n\r\n* Phí ship áp dụng cho 1 set quà, nếu quý khách đặt hơn 1 set quà phí ship sẽ được báo chính xác lại vào thời điểm giao hàng.",
                'images' => '["products/662b5f1fc32e6.webp", "products/662b5f202b225.webp"]',
                'unit' => 'giỏ',
                'quantity' => 1.00,
                'price' => 700000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 01:00:32',
                'updated_at' => '2024-05-19 01:34:25',
            ],
            [
                'id' => 14,
                'category_id' => 1,
                'vendor_id' => 1,
                'name' => 'Dâu Hàn Quốc',
                'description' => '- Xuất xứ: Hàn Quốc\r\n\r\n- Chất lượng: Nhập khẩu\r\n\r\n- Khối lượng: 250g/hộp\r\n\r\nĐặc điểm:\r\n\r\nDâu tây Hàn Quốc chinh phục khách hàng bởi hương thơm tự nhiên, vị ngọt thanh\r\n"Ngoại hình" có màu đỏ xen lẫn xanh bắt mắt, nguyên cuống xanh tươi\r\nĐóng gói với trọng lượng 250g, tiện lợi cho việc sử dụng và bảo quản\r\n- Thông tin dinh dưỡng:\r\n\r\nTăng cường hệ miễn dịch: Vitamin C trong dâu tây giúp tăng cường hệ miễn dịch, giúp cơ thể chống lại các tác nhân gây bệnh hiệu quả.\r\nHỗ trợ hệ tiêu hóa: Chất xơ trong dâu tây giúp hỗ trợ hệ tiêu hóa hoạt động trơn tru, ngăn ngừa táo bón và các vấn đề tiêu hóa khác.\r\nTốt cho tim mạch: Kali trong dâu tây giúp điều hòa huyết áp, giảm cholesterol xấu và bảo vệ tim mạch khỏe mạnh.\r\nGiúp đẹp da: Vitamin C và các chất chống oxy hóa trong dâu tây giúp dưỡng da sáng mịn, chống lão hóa và giảm nếp nhăn.\r\nHỗ trợ giảm cân: Lượng calo thấp và chất xơ cao trong dâu tây tạo cảm giác no lâu, hỗ trợ giảm cân hiệu quả và lành mạnh.\r\nNgăn ngừa ung thư: Chất chống oxy hóa dồi dào trong dâu tây giúp chống lại các gốc tự do, ngăn ngừa sự hình thành tế bào ung thư.\r\nTốt cho mắt: Vitamin A trong dâu tây giúp cải thiện thị lực, bảo vệ mắt khỏi các bệnh về mắt như đục thủy tinh thể và thoái hóa điểm vàng.\r\nHỗ trợ sức khỏe răng miệng: Chất xơ trong dâu tây giúp loại bỏ mảng bám và vi khuẩn trong khoang miệng, ngăn ngừa sâu răng và các bệnh về nướu.\r\nGiúp xương chắc khỏe: Kali trong dâu tây giúp tăng cường mật độ xương, ngăn ngừa loãng xương.\r\n- Hướng dẫn sử dụng:\r\n\r\nRửa nhẹ nhàng dâu tây và loại bỏ mũ lá khi bạn rửa xong. \r\nBạn có thể thưởng thức dâu tươi trực tiếp hoặc chấm thêm sữa chua, mật ong để tăng thêm hương vị.\r\nCó thể kết hợp dâu với các loại trái cây khác như chuối, kiwi, táo,... để tạo nên những ly sinh tố thơm ngon, bổ dưỡng.\r\nDâu cũng có thể được thêm vào các món salad gà nướng, salad cá hồi,... để tăng thêm hương vị và giá trị dinh dưỡng.\r\nBạn cũng có thể làm mứt dâu, kem dâu để ăn kèm với bánh mì, yogurt hoặc sử dụng trong các món tráng miệng khác.\r\nDâu cũng có thể được kết hợp với phô mai, giấm balsamic để làm món khai vị thanh tao và đầy tinh tế.\r\nVị ngọt thanh của dâu hòa quyện với các loại rượu, nước trái cây khác tạo nên thức uống độc đáo và sảng khoái.\r\n- Cách bảo quản: \r\n\r\nKhi được bảo quản đúng cách tại nhà, dâu tây có thể tươi từ 2 - 4 ngày sau khi mua. \r\nGiữ lạnh dâu tây giúp bảo quản lâu hơn. \r\nChúng tôi giữ các loại quả mọng trong tủ lạnh và đặc biệt khuyên bạn nên giữ chúng trong hộp đựng ban đầu và làm lạnh chúng càng sớm càng tốt. \r\nKhông rửa trước khi cho vào tủ lạnh.\r\n- Cách lựa chọn dâu: \r\n\r\nQuan sát phần cuống của dâu: Nếu cuống dâu còn xanh và dính chặt vào quả thì đây là dấu hiệu của quả dâu tươi ngon.\r\nNhẹ nhàng ấn vào quả dâu: Nếu quả dâu có độ đàn hồi tốt và không bị dập nát thì đây là dấu hiệu của quả dâu tươi ngon.',
                'images' => '["products/6635f2dbd48ec.webp", "products/6635f2dcf0b12.webp", "products/6635f2ddd4dcb.webp"]',
                'unit' => 'kg',
                'quantity' => 7.90,
                'price' => 229000,
                'discount' => 0.15,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 01:33:34',
                'updated_at' => '2024-05-16 23:33:53',
            ],
            [
                'id' => 15,
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Quýt nội địa Trung',
                'description' => 'Tên sản phẩm: Quýt nội địa Trung Quốc - 800G/Túi\r\nLoại sản phẩm: Trái cây tươi\r\nXuất xứ: Trung Quốc\r\nTrọng lượng: 800g/Túi\r\nĐặc điểm:\r\nVỏ quýt có màu vàng cam sáng, mỏng, dễ bóc.\r\nThịt quýt màu vàng óng, mọng nước, vị ngọt thanh, có chút chua nhẹ.\r\nVỏ rất dễ bóc, khi bóc quýt có mùi thơm đặc trưng, vị ngọt, mọng nước.\r\nGiá trị dinh dưỡng:\r\nGiàu vitamin C, vitamin B1, B2, kali, chất xơ,...\r\nTốt cho hệ miễn dịch, hệ tiêu hóa, tim mạch, da và mắt.\r\nChống oxy hóa, ngăn ngừa ung thư.\r\nCông dụng:\r\nĂn tươi, làm sinh tố, salad, nước ép,...\r\nCó thể bảo quản được lâu.',
                'images' => '["products/6635f66e91885.webp", "products/6635f66fc815b.webp", "products/6635f670c5909.webp"]',
                'unit' => 'kg',
                'weight' => 5.40,
                'price' => 89000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 01:48:49',
                'updated_at' => '2024-05-17 23:48:13',
            ],
            [
                'id' => 16,
                'category_id' => 2,
                'brand_id' => 3,
                'name' => 'Vải trứng Daklak có cành',
                'description' => 'Chùm đầy, trái to, cơm dày, vị chua ngọt của đầu mùa.\r\n \r\nVải trứng Daklak có cành - 1Kg là một loại trái cây thơm ngon, được nhiều người yêu thích bởi hương vị ngọt thanh, đậm đà và mọng nước. Vải Daklak được trồng tại tỉnh Daklak, nơi có khí hậu và thổ nhưỡng phù hợp để cây vải phát triển tốt nhất. Vải Daklak có vỏ màu đỏ tía, dày, khi chín chuyển sang màu đỏ sẫm. Cùi vải màu trắng ngà, dày, mịn và có vị ngọt thanh, đậm đà. Vải Daklak thường được ăn tươi hoặc dùng để chế biến các món ăn khác như sinh tố, nước ép, chè,…\r\nTên sản phẩm: Vải trứng Daklak có cành - 1Kg\r\n\r\nXuất xứ: Daklak, Việt Nam\r\n\r\nTrọng lượng: 1Kg\r\n\r\nĐặc điểm: Vỏ màu đỏ tía, dày, khi chín chuyển sang màu đỏ sẫm. Cùi vải màu trắng ngà, dày, mịn và có vị ngọt thanh, đậm đà.\r\n\r\nCách sử dụng: Ăn tươi hoặc dùng để chế biến các món ăn khác như sinh tố, nước ép, chè,…\r\n\r\nBảo quản: Nơi khô ráo, thoáng mát, tránh ánh nắng trực tiếp.',
                'images' => '["products/6635f785583b4.webp"]',
                'unit' => 'kg',
                'weight' => 7.40,
                'price' => 129000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 01:53:25',
                'updated_at' => '2024-05-16 23:33:53',
            ],
            [
                'id' => 17,
                'category_id' => 2,
                'brand_id' => 3,
                'name' => 'Sầu riêng cơm Musang King Việt Nam',
                'description' => 'Sầu Musang King có màu vàng đậm rất mịn không có sợi, thịt cơm liên kết với nhau rất chắc. Sầu riêng mang một hương vị đậm đà, hương thơm đặc trưng.',
                'images' => '["products/6635f84498575.webp"]',
                'unit' => 'kg',
                'weight' => 6.30,
                'price' => 318750,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 01:56:37',
                'updated_at' => '2024-05-18 17:05:22',
            ],
            [
                'id' => 18,
                'category_id' => 2,
                'brand_id' => 3,
                'name' => 'Mận xanh Tam Hoa',
                'description' => 'Mận xanh ruột trắng, vị ngọt thanh. Chấm muối ăn rất cuốn',
                'images' => '["products/6635f8f1dc186.webp"]',
                'unit' => 'kg',
                'weight' => 7.60,
                'price' => 89000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 01:59:30',
                'updated_at' => '2024-05-17 23:51:15',
            ],
            [
                'id' => 19,
                'category_id' => 1,
                'brand_id' => 4,
                'name' => 'Nho đỏ Long Crimson Úc',
                'description' => 'Xuất xứ: Úc\r\n\r\nTiêu chuẩn chất lượng: Nhập khẩu\r\n\r\nĐiểm đặc biệt nổi bật: \r\n\r\nNho Long Crimson quả dài, không hạt, vỏ ngoài màu đỏ mọng, và vị ngọt xen kẽ vị chua nhẹ.\r\nĂn nho có tác dụng tăng cường sức khỏe tim mạch, bổ mắt, giảm tốc độ lão hóa, tăng cường miễn dịch.\r\nCó thể ăn trực tiếp, làm nước ép, sinh tố, làm bánh, sữa chua...\r\nNho Đỏ Không Hạt Long Crimson Úc là một trong những loại nho ngon nhất trên thế giới mà bất cứ ai cũng yêu thích, với hính dáng thuôn dài, ngọt xen kẽ vị chua rất nhẹ và hương thơm nồng nàn tuyệt vời. Chính bởi hương vị đặc biệt, nó được xếp vào danh sách trái cây nhập khẩu ngon nhất mà bạn nhất định phải thưởng thức một lần trong đời \r\n\r\nThông tin dinh dưỡng:\r\n\r\nTăng cường sức khỏe cho tim mạch: ngăn chặn sự tích kết tụ tiểu huyết cầu, tăng đàn hồi và chức năng của động mạch, giảm các triệu chứng viêm nhiễm, ngừa nguy cơ xơ cứng động mạch, giảm huyết áp.\r\nTốt cho thị giác nhờ Vitamin A và hợp chất flavonol. Giúp tổng hợp chất dinh dưỡng và có tác dụng kiểm soát sự trao đổi chất nhờ chứa nhiều vitamin B.\r\nResveratrol trong vỏ nho là chất chống oxy hóa mạnh gấp 7 lần vitamin E có tác dụng bảo vệ tế bào bằng cách trung hòa các tác nhân phá hoại của các phân tử tự do. Làm chậm quá trình oxy hóa, phòng chống các bệnh về tuổi già.\r\nĂn Crimson có tác dụng chữa chứng đau nửa đầu, tăng cường hệ miễn dịch, phòng chống các bệnh lây qua đường hô hấp',
                'images' => '["products/6635f9abf06a9.webp", "products/6635f9ad041d2.webp", "products/6635f9adbc7c9.webp"]',
                'unit' => 'kg',
                'weight' => 8.90,
                'price' => 104500,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:02:38',
                'updated_at' => '2024-05-08 06:58:00',
            ],
            [
                'id' => 20,
                'category_id' => 2,
                'brand_id' => 5,
                'name' => 'Dưa lưới TL3',
                'description' => 'Xuất xứ: giống Nhật, trồng tại Việt Nam\r\n\r\nĐặc điểm: Dưa lưới TL3 được trồng đạt chất lượng trái tròn đều, đầy thịt, ngọt mọng nước cùng hương thơm đậm đà.',
                'images' => '["products/6635fa4f10d65.webp"]',
                'unit' => 'kg',
                'weight' => 7.50,
                'price' => 210000,
                'discount' => 0.22,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:05:19',
                'updated_at' => '2024-05-17 23:51:15',
            ],
            [
                'id' => 21,
                'category_id' => 2,
                'brand_id' => 6,
                'name' => 'Ổi nữ hoàng',
                'description' => 'Đặc điểm :\r\n\r\nỔi nữ hoàng có thịt quả khá dày và ruột rất nhỏ có một ít hạt.\r\nỔi có mùi thơm mát, giòn và ngọt đặc trưng.\r\nĐược tuyển chọn khắt khe, đảm bảo vệ sinh thực phẩm.\r\nỔi Nữ Hoàng có dạng hình cầu tròn, trái to, phần thịt quả khá dày và ruột rất nhỏ có một ít hạt. Ổi tỏa ra một mùi thơm mát đặc trưng, khi ăn bạn sẽ cảm nhận được độ giòn và ngọt nơi đầu lưỡi cho đến khi ăn hết quả. Đây là những trái ổi được tuyển chọn khắt khe, đảm bảo vệ sinh thực phẩm cho người tiêu dùng.',
                'images' => '["products/6635fae80f329.webp"]',
                'unit' => 'kg',
                'weight' => 8.00,
                'price' => 45000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:07:52',
                'updated_at' => '2024-05-17 23:51:15',
            ],
            [
                'id' => 22,
                'category_id' => 2,
                'brand_id' => 6,
                'name' => 'Xoài cát hòa lộc',
                'description' => 'Xoài Cát Hoà Lộc nổi tiếng của Việt Nam, có những đặc trưng nổi bật như: \r\n\r\n- Xoài Cát Hòa Lộc trái to, chắc tay khoảng 500G/trái.\r\n- Thịt dày, vàng ươm, ngọt thơm, đậm vị, không xơ hoặc rất ít.\r\n- Hàng tuyển chọn, nhập tận vườn miền Tây. Đảm bảo đem đến nguồn trái cây sạch và chất lượng tuyệt vời khi đến tay người tiêu dùng.',
                'images' => '["products/6635fb2755e81.webp"]',
                'unit' => 'kg',
                'weight' => 5.50,
                'price' => 149000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:08:55',
                'updated_at' => '2024-05-18 17:05:12',
            ],
            [
                'id' => 23,
                'category_id' => 2,
                'brand_id' => 6,
                'name' => 'Bơ sáp',
                'description' => 'Xuất xứ: Việt Nam\r\n\r\nQuy cách: 1Kg\r\n\r\nHướng dẫn cách bảo quản bơ để giữ bơ thơm ngon lâu\r\n\r\nĐể bơ sáp luôn giữ được hương bị tươi ngon, bạn cần tuân thủ một số lưu ý cần thiết trong cách bảo quản bơ như sau:\r\n\r\nKhông nên nắn bơ quá nhiều.\r\nĐể bơ ở nơi mát, nhiệt độ lý tưởng là từ 23-25 độ C.\r\nTốt nhất nên để bơ tiếp xúc với mặt đất, không để bơ trong túi ni-lông vì bơ rất dễ bị thối.\r\nNếu bơ đã mềm nên cho bơ vào ngăn mát tủ lạnh để bảo quản. Tuy nhiên không nên để bơ trong tủ lạnh quá lâu.\r\nNếu cắt bơ nhưng chưa kịp sử dụng thì nên bôi lên bề mặt miếng bơ một lớp dầu mỏng rồi bọc kín bằng màng bọc thực phẩm, bảo quản trong tủ lạnh để dùng dần.\r\nCó thể dùng báo bọc quả bơ để làm chậm quá trình bơ phân hủy, cách này giúp bơ tươi lâu hơn.\r\nNếu bơ chín nhiều mà bạn thưởng thức không kịp, hãy cắt bơ thành từng lát rồi bỏ vào hộp nhựa rồi cho vào ngăn đá. Khi ăn thì chờ bơ tan ra, hương vị cũng rất thơm ngon.',
                'images' => '["products/6635fb78208e7.webp"]',
                'unit' => 'kg',
                'weight' => 8.20,
                'price' => 99000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:10:16',
                'updated_at' => '2024-05-17 23:51:15',
            ],
            [
                'id' => 24,
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Việt quất Mỹ',
                'description' => 'Việt quất Mỹ size Regular - 125g/Hộp\r\n- Xuất xứ: Mỹ\r\n- Tiêu chuẩn chất lượng: Nhập khẩu\r\n\r\n- Đặc điểm:\r\n\r\nViệt quất Mỹ size Regular có kích thước trung bình, trái đều đặn, vỏ căng mịn, màu xanh đậm.\r\nThịt quả mềm, mọng nước, vị ngọt thanh xen lẫn chút chua dịu\r\n- Thông tin dinh dưỡng:\r\n\r\nTăng cường hệ miễn dịch: Vitamin C trong việt quất giúp tăng cường hệ miễn dịch, giúp cơ thể chống lại các tác nhân gây bệnh hiệu quả.\r\nHỗ trợ hệ tiêu hóa: Chất xơ trong việt quất giúp hỗ trợ hệ tiêu hóa hoạt động trơn tru, ngăn ngừa táo bón và các vấn đề tiêu hóa khác.\r\nTốt cho tim mạch: Kali trong việt quất giúp điều hòa huyết áp, giảm cholesterol xấu và bảo vệ tim mạch khỏe mạnh.\r\nGiúp đẹp da: Vitamin C và các chất chống oxy hóa trong việt quất giúp dưỡng da sáng mịn, chống lão hóa và giảm nếp nhăn.\r\nHỗ trợ giảm cân: Lượng calo thấp và chất xơ cao trong việt quất tạo cảm giác no lâu, hỗ trợ giảm cân hiệu quả và lành mạnh.\r\nNgăn ngừa ung thư: Chất chống oxy hóa dồi dào trong việt quất giúp chống lại các gốc tự do, ngăn ngừa sự hình thành tế bào ung thư.\r\nTốt cho mắt: Vitamin A trong việt quất giúp cải thiện thị lực, bảo vệ mắt khỏi các bệnh về mắt như đục thủy tinh thể và thoái hóa điểm vàng.\r\nHỗ trợ sức khỏe răng miệng: Chất xơ trong việt quất giúp loại bỏ mảng bám và vi khuẩn trong khoang miệng, ngăn ngừa sâu răng và các bệnh về nướu.\r\nGiúp xương chắc khỏe: Kali trong việt quất giúp tăng cường mật độ xương, ngăn ngừa loãng xương.\r\n- Hướng dẫn sử dụng:\r\n\r\nRửa nhẹ nhàng việt quất với nước sạch để loại bỏ phần phấn trắng trên vỏ.\r\nViệt quất Mỹ size Regular là nguyên liệu tuyệt vời để làm sinh tố và nước ép.\r\nViệt quất Mỹ size Regular được sử dụng để trang trí bánh kem, bánh mousse, bánh tart,... tạo điểm nhấn đẹp mắt và tăng thêm hương vị cho món bánh.\r\nViệt quất Mỹ size Regular cắt nhỏ, trộn với các loại rau củ quả khác cùng với nước sốt yêu thích để tạo thành món salad thanh mát và đầy đủ dưỡng chất.\r\nViệt quất Mỹ size Regular có thể được sử dụng để làm nước sốt cho các món ăn như thịt nướng, cá kho,... tạo nên hương vị độc đáo và hấp dẫn.\r\nViệt quất Mỹ size Regular có thể được sử dụng để làm nước sốt cho các món ăn như thịt nướng, cá kho,... tạo nên hương vị độc đáo và hấp dẫn.\r\nBạn có thể làm mặt nạ việt quất bằng cách nghiền nhuyễn việt quất và trộn với sữa chua, mật ong,... để đắp lên mặt trong 15-20 phút.\r\n- Cách chọn việt quất:\r\nNên chọn những quả việt quất có hình dáng đều đặn, tròn trịa, không bị dập nát hay có dấu hiệu hư hỏng.\r\nViệt quất Mỹ size Regular khi chín tới sẽ có độ mềm vừa phải, khi ấn nhẹ vào sẽ cảm nhận được độ giòn tan.\r\nNên chọn những quả việt quất có mùi thơm rõ ràng, không bị mùi hôi hoặc mùi chua.\r\nVới Farmers Market tiêu chí hàng đầu là sản phảm đạt chất lượng cao, nguồn gốc rõ ràng, mang đến trải nghiệm tốt nhất cho khách hàng. \r\n- Những lưu ý khi xử dụng việt quất:\r\nRửa sạch việt quất Mỹ size Regular kỹ trước khi ăn.\r\nNên ăn với lượng vừa phải, khoảng 100-150g mỗi ngày.\r\nTrẻ em dưới 1 tuổi không nên ăn việt quất nguyên quả. Nên xay nhuyễn việt quất hoặc trộn vào sữa chua, sinh tố để trẻ dễ ăn.\r\n- Phụ nữ mang thai và trẻ em ăn việt quất có được không?\r\nViệt quất giúp cung cấp vitamin C, folate, vitamin K, kali, chất xơ và các chất chống oxy hóa cần thiết cho sự phát triển của thai nhi.\r\nVitamin C giúp tăng cường hệ miễn dịch, hỗ trợ hấp thu sắt và collagen.\r\nFolate giúp ngăn ngừa dị tật ống thần kinh ở thai nhi.\r\nVitamin K giúp phát triển xương thai nhi.\r\nKali giúp điều hòa huyết áp, giảm nguy cơ chuột rút.\r\nTrẻ em dưới 1 tuổi không nên ăn việt quất nguyên quả. Nên xay nhuyễn việt quất hoặc trộn vào sữa chua, sinh tố để trẻ dễ ăn.',
                'images' => '["products/6635fbd475224.webp", "products/6635fbd512f47.webp", "products/6635fbd5ec802.webp"]',
                'unit' => 'kg',
                'weight' => 9.70,
                'price' => 278000,
                'discount' => 0.20,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:11:50',
                'updated_at' => '2024-05-16 23:43:57',
            ],
            [
                'id' => 25,
                'category_id' => 2,
                'brand_id' => 6,
                'name' => 'Dưa hấu đỏ không hạt',
                'description' => 'Dưa Hấu Đỏ Không Hạt thuộc giống dưa không hạt, mọng nước hơn và ngọt đậm. Dưa được trồng và thu hoạch đạt tiêu chuẩn an toàn thực phẩm, đảm bảo cho người tiêu dùng. \r\n\r\nQuy cách: 3.5Kg - 4Kg/Trái\r\n\r\nHướng dẫn sử dụng\r\n\r\nDưa hấu có thể ăn trực tiếp, làm nước ép, xay sinh tố.\r\nDưa hấu ngon hơn khi ướp lạnh trước khi ăn.',
                'images' => '["products/6635fc2e9a3fe.webp"]',
                'unit' => 'kg',
                'weight' => 3.90,
                'price' => 156000,
                'discount' => 0.12,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:13:19',
                'updated_at' => '2024-05-18 17:05:22',
            ],
            [
                'id' => 26,
                'category_id' => 2,
                'brand_id' => 4,
                'name' => 'Đu đủ',
                'description' => 'Đặc Điểm:\r\n\r\nLà loại đu đủ ngon nhất Việt Nam\r\nCơm dày, màu vàng ươm, ngọt đậm\r\nĐu Đủ A Cón được đánh giá là loại đu đủ có vị ngọt, cơm vàng và ngon hơn hẳn những loại đu đủ thông thường. Đây cũng là loại đu đủ ngon nhất Việt Nam hiện nay. Đu đủ được trồng hoàn toàn theo hướng hữu cơ bằng giống thuần chủng do chú A Cón tự nhân giống.',
                'images' => '["products/6635fc6b710d2.webp"]',
                'unit' => 'kg',
                'weight' => 10.00,
                'price' => 43500,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:14:20',
                'updated_at' => '2024-05-05 00:51:47',
            ],
            [
                'id' => 27,
                'category_id' => 2,
                'brand_id' => 4,
                'name' => 'Mận đỏ An Phước',
                'description' => 'Đặc Điểm:\r\n\r\nCó vị ngọt dịu, giòn xốp, khá mọng nước.\r\nNhiều nước và vitamin\r\nMận Đỏ An Phước (KG) là một trái cây quen thuộc được nhiều người yêu thích bởi tác dụng thanh nhiệt. Mận được trồng tại An Phước với màu đỏ và bóng, trái to vừa và ngọt thanh, tỉ lệ gặp trái có vị chua rất ít (trừ trái còn xanh, chưa chín).',
                'images' => '["products/6635fcb2f2fde.webp", "products/6635fcb386101.webp", "products/6635fcb3d0b80.webp"]',
                'unit' => 'kg',
                'weight' => 8.80,
                'price' => 78000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:15:31',
                'updated_at' => '2024-05-16 23:45:54',
            ],
            [
                'id' => 28,
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Măng cụt Thái Lan',
                'description' => 'Măng cụt Thái Lan', 'Măng cụt Thái Lan\r\n- Xuất xứ: Thái Lan\r\n- Tiêu chuẩn chất lượng: Trái cây sạch\r\n\r\n- Đặc Điểm:\r\n\r\nCó vỏ ngoài màu đỏ, cơm trắng đục, vị ngọt đậm xen chút chua nhẹ đặc trưng.\r\nRất giàu vitamin C, B1, ocarbonhydrates, chất xơ, calsium, chất sắt, phốt pho.\r\nĂn măng cụt có tác dụng giải nhiệt, giảm huyết áp, cải thiện sinh lực, chống viêm.\r\nCó thể ăn trực tiếp, làm sinh tố, hoặc sấy khô làm mứt.\r\n- Thông tin dinh dưỡng:\r\n\r\nMăng cụt tính mát, giúp thanh lọc cơ thể, giải nhiệt và làm dịu căng thẳng.\r\nGiảm huyết áp và ngăn sự tấn công huyết áp của mạch máu đường phổi.\r\nKháng thể Xanthones trong măng cụt có tác dụng làm giảm tác dụng gây lão hóa của cholesterol xấu và ngăn ngừa sự hình thành các mảng bám nguy hiểm.\r\nNgăn ngừa bệnh tiểu đường: Với khả năng làm giảm và điều hòa lượng đường trong máu, cải thiện sinh lực, chống viêm, măng cụt rất cần thiết cho bệnh nhân tiểu đường.\r\n- Hướng dẫn sử dụng:\r\nMăng cụt Thái Lan có thể ăn trực tiếp hoặc chế biến thành nhiều món ăn ngon như salad, sinh tố, mứt,...\r\nMăng cụt Thái Lan cũng có thể được sử dụng để trang trí các món ăn.\r\n- Cách lựa chọn:\r\nNên chọn mua măng cụt Thái Lan có vỏ căng bóng, màu nâu đỏ đều, sần sùi, không bị dập nát hay có dấu hiệu hư hỏng.\r\nVới Farmers Market tiêu chí hàng đầu là sản phảm đạt chất lượng cao, nguồn gốc rõ ràng, mang đến trải nghiệm tốt nhất cho khách hàng. \r\n- Hướng dẫn bảo quản\r\n\r\nMăng cụt là một trong những loại trái cây khó bảo quản vì nếu để quá lâu dễ bị chai cứng và ăn không ngon như lúc vừa mới hái. Vì thế, để bảo quản măng cụt tươi ngon, ngoài việc chọn mua măng cụt ở những nơi uy tín, có nguồn gốc rõ ràng, thì bạn cũng nên áp dụng một số mẹo bảo quản như sau:\r\n\r\nKhông nên rửa măng cụt trước khi bảo quản vì sẽ khiến măng cụt nhanh bị hỏng.\r\nKhi mua về, nếu măng cụt chưa chín tới, bạn có thể bảo quản ở nhiệt độ phòng thoáng mát, tránh ánh nắng trực tiếp.\r\nMăng cụt đã chín nên bảo quản trong ngăn mát tủ lạnh\r\nKhông nên bảo quản măng cụt chung với các loại trái cây khác như táo, chuối vì có thể khiến măng cụt nhanh chín và bị mềm để giữ độ tươi ngon.\r\n- Phụ nữ mang thai và trẻ em ăn măng cụt có được không?\r\n+ Các chuyên gia đều cho rằng bầu có thể ăn măng cụt với 1 lượng vừa đủ để có thể cung cấp lượng vitamin, khoáng chất đặc biệt là folic dồi dào giúp phát triển thai nhi tốt hơn, tránh suy dinh dưỡng bào thai và dị tật bẩm sinh.\r\n\r\n+ Có thể cho trẻ ăn măng cụt khi bé đủ 6 tháng tuổi. Măng cụt là nguồn cung cấp vitamin C, chất xơ và kali dồi dào, tốt cho sức khỏe của trẻ\r\n\r\n- Những lưu ý khi dùng: \r\n\r\nMỗi lần nên cho trẻ ăn từ 1-2 quả măng cụt và ăn sau bữa chính 30 phút.\r\nBầu ăn măng cụt với lượng vừa phải, khoảng 3-4 quả mỗi ngày.\r\nKhông nên ăn quá nhiều có thể làm tăng nguy cơ nhiễm axit lactic ảnh hưởng đến dạ dày và hệ tiêu hóa\r\nTrong măng cụt có hợp chất xanthone có ảnh hưởng đến khả năng đông máu tự nhiên của cơ thể, do đó bầu nên ngưng ăn tối thiểu trước 2 tuần sinh',
                'images' => '["products/6635fd07baef9.webp", "products/6635fd0937f28.webp", "products/6635fd0a0b906.webp"]',
                'unit' => 'kg',
                'weight' => 8.50,
                'price' => 59500,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:16:58',
                'updated_at' => '2024-05-18 16:53:10',
            ],
            [
                'id' => 29,
                'category_id' => 2,
                'brand_id' => 5,
                'name' => 'Chuối Dole 3 trái',
                'description' => 'Đặc Điểm:\r\n\r\nChuối DOLE, thương hiệu chuối nổi tiếng thế giới được người tiêu dùng trong và ngoài nước tin dùng.\r\nLà một giống chuối ngoại nhập, có mùi thơm và có vị ngọt đặc trưng.\r\nChuối Dole (3 trái) có mùi thơm, dẻo và ngọt đặc trưng với màu vàng bắt mắt. Đây là giống chuối ngoại nhập được nhiều người săn đón nhờ hương vị tuyệt hảo, màu sắc hấp dẫn và nhiều chất dinh dưỡng. Chuối Dole đem đến cho cơ thể nguồn năng lượng dồi dào, để có thể luôn tràn đầy sức sống mỗi ngày.\r\n\r\nQuy cách: Nhánh 3 trái',
                'images' => '["products/6635fd41a4887.webp"]',
                'unit' => 'kg',
                'weight' => 5.40,
                'price' => 29000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:17:54',
                'updated_at' => '2024-05-17 23:46:48',
            ],
            [
                'id' => 30,
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Lựu đỏ Peru',
                'description' => 'Lựu đỏ Peru size Jumbo \r\n- Xuất xứ: Peru\r\n\r\n- Tiêu chuẩn chất lượng: Nhập khẩu\r\n\r\n- Đặc điểm:\r\n\r\nKích thước: Jumbo, quả to, thường nặng 800g - 850g/trái\r\nMàu sắc: Vỏ đỏ tươi, bên trong hạt màu đỏ ruby đẹp mắt\r\nHương vị: Ngọt đậm, mọng nước, vị chua dịu\r\n- Giá trị dinh dưỡng:\r\n\r\nGiàu chất chống oxy hóa: Polyphenol, anthocyanin giúp tăng cường hệ miễn dịch, chống lão hóa, giảm nguy cơ mắc bệnh tim mạch, ung thư.\r\nChứa nhiều vitamin: Vitamin C, A, E, K tốt cho sức khỏe mắt, da, hệ miễn dịch và xương khớp.\r\nGiàu khoáng chất: Kali, magie, sắt tốt cho tim mạch, hệ thần kinh và máu.\r\nChất xơ: Hỗ trợ tiêu hóa, giảm cholesterol.\r\nKali: Giúp điều hòa huyết áp.\r\n- Hướng dẫn sử dụng\r\n\r\nRửa nhẹ nhàngvỏ ngoài của lựu.\r\nCách tách hạt lựu ra khỏi lớp vỏ quả nhanh nhất là tách quả lựu thành từng khía mỏng, sau đó dùng muỗng đập nhẹ lên lớp võ, những hạt lựu sẽ từ từ rơi ra hết.\r\nGiữ lạnh lựu giúp bảo quản lâu hơn.\r\n- Hướng dẫn sử dụng:\r\n\r\nPhương pháp truyền thống:\r\nCắt ngang quả lựu thành hai phần theo chiều ngang.\r\nDùng muỗng gõ nhẹ vào vỏ lựu để tách hạt rơi ra.\r\nNhặt bỏ phần cùi trắng và vỏ còn sót lại.\r\nPhương pháp sử dụng nước:\r\nCắt ngang quả lựu thành hai phần theo chiều ngang.\r\nCho lựu vào tô nước và ngâm trong vài phút.\r\nDùng tay bóp nhẹ vỏ lựu để tách hạt ra.\r\nVớt hạt lựu ra khỏi nước và để ráo.\r\nLựu có thể ăn trực tiếp, làm nước ép, sinh tố, salad\r\n- Cách lựa chọn:\r\n\r\nKhách hàng nên chọn những quả nho có vỏ căng bóng, màu sắc tươi sáng, không bị dập nát hay có dấu hiệu thối rữa.\r\n\r\nVới Farmers Market tiêu chí hàng đầu là sản phảm đạt chất lượng cao, nguồn gốc rõ ràng, mang đến trải nghiệm tốt nhất cho khách hàng.',
                'images' => '["products/6635fda8d2cf7.webp", "products/6635fdaa22ecf.webp", "products/6635fdab0eb14.webp"]',
                'unit' => 'kg',
                'weight' => 8.30,
                'price' => 254250,
                'discount' => 0.18,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:19:39',
                'updated_at' => '2024-05-18 16:56:37',
            ],
            [
                'id' => 31,
                'category_id' => 2,
                'brand_id' => 6,
                'name' => 'Thanh long ruột đỏ',
                'description' => 'Thanh long ruột đỏ (1KG)\r\n\r\nXuất xứ: Việt Nam\r\n\r\nTrọng lượng sản phẩm: 1KG\r\n\r\nĐặc Điểm:\r\n\r\nTrái cây Việt canh tác an toàn, tuyển chọn loại nhất\r\nCó ruột đỏ, ngọt, giàu dinh dưỡng hơn thanh long trắng',
                'images' => '["products/6635fdf98c07f.webp"]',
                'unit' => 'kg',
                'weight' => 8.60,
                'price' => 89000,
                'discount' => 0.20,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:20:58',
                'updated_at' => '2024-05-17 23:46:48',
            ],
            [
                'id' => 32,
                'category_id' => 2,
                'brand_id' => 4,
                'name' => 'Bưởi đường lá cam Tân Triều',
                'description' => 'Xuất xứ: Việt Nam\r\n\r\nTiêu chuẩn chất lượng: Trái cây sạch\r\n\r\nKhối lượng: (0,9 - 1.2Kg/Trái)\r\n\r\nĐặc điểm nổi bật:\r\n\r\nVỏ mỏng, mọng nước, vị đậm đà, múi bưởi dẻo khác hẵn các loại bưởi khác, có thể để được rất lâu từ 20 - 30 ngày mà không hư, khi bưởi chín vỏ trái dần chuyển sang màu vàng, lúc này bưởi rất thơm, kể cả không cần lột vỏ cũng có thể ngửi được mùi thơm',
                'images' => '["products/6635fe4f21b59.webp", "products/6635fe4f9078f.webp", "products/6635fe4fc0464.webp"]',
                'unit' => 'kg',
                'weight' => 5.50,
                'price' => 37000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:22:23',
                'updated_at' => '2024-05-18 16:56:37',
            ],
            [
                'id' => 33,
                'category_id' => 2,
                'brand_id' => 3,
                'name' => 'Đu đủ ruột đỏ giống Đài Loan',
                'description' => 'Xuất xứ: Việt Nam\r\nTrọng lượng sản phẩm: 1KG\r\nĐặc điểm nổi bật: Đu đủ là một loại trái cây mà gia đình thường lựa chọn để ăn.',
                'images' => '["products/6635feda90e24.webp"]',
                'unit' => 'kg',
                'weight' => 8.60,
                'price' => 45000,
                'discount' => 0.25,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:24:08',
                'updated_at' => '2024-05-18 00:57:58',
            ],
            [
                'id' => 34,
                'category_id' => 3,
                'brand_id' => 5,
                'name' => 'Giỏ Trái Cây Nhập Healthy Living',
                'description' => 'Giỏ quà bao gồm:\r\n- Dưa lưới ruột cam Pansy Globalgap loại 1 (1 trái khoảng 1,7kg) \r\n- Quýt Ai Cập (5 trái khoảng 1 kg) \r\n- Táo Envy Mỹ size 100 - 113 (6 trái khoảng 1,2kg) \r\n- Lê Nam Phi (3 trái khoảng 700g) \r\n- Hộp giấy Healthy Living vân gỗ 36 x 27 x 12 cm \r\n- Túi giấy nằm Farmers Market Tết 2024 ( 44 x 25.5 x 29 )',
                'images' => '["products/6635ff55d1307.webp", "products/6635ff5657cba.webp"]',
                'unit' => 'giỏ',
                'weight' => 0.00,
                'price' => 1200000,
                'discount' => 0.00,
                'status' => 'Tạm hết hàng',
                'created_at' => '2024-05-04 02:26:46',
                'updated_at' => '2024-05-05 00:56:19',
            ],
            [
                'id' => 35,
                'category_id' => 3,
                'brand_id' => 5,
                'name' => 'Hộp Quà Trái Cây Nhập Màu Hồng Hoạ Tiết Vàng',
                'description' => 'Set quà bao gồm:\r\n- Nho xanh Autumn Crissp (1kg)\r\n- Quýt nội địa Trung size M (2 trái, khoảng 360g)\r\n- Cam vàng Navel (1 trái, khoảng 400g)\r\n- Táo xanh Granny Smith Mỹ | Size 90 - 100 (1 trái, khoảng 200g)\r\n- Lê nâu nội địa Trung (1 trái, khoảng 400g)\r\n- Kiwi vàng New Zealand size XL (2 trái khoảng 320g)\r\n- Táo Envy Mỹ | Size 24 - 28 (1 trái, khoảng 400g)\r\n- Dâu Hàn Quốc (1 hộp 250g)\r\n- Hộp quà hồng hoạ tiết vàng (34 x 25 x 11cm)',
                'images' => '["products/6635ffd29730b.webp"]',
                'unit' => 'giỏ',
                'weight' => 0.00,
                'price' => 1100000,
                'discount' => 0.00,
                'status' => 'Tạm hết hàng',
                'created_at' => '2024-05-04 02:28:51',
                'updated_at' => '2024-05-05 00:56:19',
            ],
            [
                'id' => 36,
                'category_id' => 3,
                'brand_id' => 5,
                'name' => 'Giỏ Trái Cây Nhập Lục Bình',
                'description' => 'Giỏ quà bao gồm:\r\n- Việt Quất nội địa Trung 145g (1 hộp) \r\n- Cam vàng Navel Mỹ (5 trái khoảng 1,5kg) \r\n- Lê nâu nội địa Trung (2 trái khoảng 800g) \r\n- Kiwi vàng New Zealand size XL (6 trái khoảng 1kg) \r\n- Nho xanh Autumn Crisp Úc (khoảng 500g) \r\n- Táo Envy Mỹ size 100 - 113 (5 trái khoảng 800g) \r\n- Dưa lưới ruột cam Pansy Globalgap loại 1 (1 trái khoảng 1,8kg) \r\n- Giỏ đan lục bình 2 tầng màu nâu 39x29x16 \r\n- Túi giấy nằm Farmers Market Tết 2024 ( 44 x 25.5 x 29 )',
                'images' => '["products/6636000aedafc.webp", "products/6636000b55512.webp"]',
                'unit' => 'giỏ',
                'weight' => 0.00,
                'price' => 1700000,
                'discount' => 0.00,
                'status' => 'Tạm hết hàng',
                'created_at' => '2024-05-04 02:29:47',
                'updated_at' => '2024-05-05 00:56:19',
            ],
        ]);
    }
}
