<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 5,
                'category_id' => 1,
                'vendor_id' => 1,
                'name' => 'Táo Envy Mỹ',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635f05c93df4.webp", "products/6635f05cc1964.webp", "products/6635f05d031c2.webp"]',
                'unit' => 'kg',
                'quantity' => 7.40,
                'price' => 161400,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:44:34',
                'updated_at' => '2024-05-19 01:32:48',
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'vendor_id' => 1,
                'name' => 'Cherry đỏ Mỹ',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635ed3a42000.webp"]',
                'unit' => 'kg',
                'quantity' => 4.90,
                'price' => 89000,
                'discount' => 0.10,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:52:16',
                'updated_at' => '2024-05-18 16:53:10',
            ],
            [
                'id' => 7,
                'category_id' => 1,
                'vendor_id' => 6,
                'name' => 'Nho mẫu đơn Premium Hàn Quốc',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/662b5d77ce4f1.webp", "products/662b5d782d7c2.webp", "products/662b5d784a8bb.webp"]',
                'unit' => 'kg',
                'quantity' => 8.00,
                'price' => 399000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:53:28',
                'updated_at' => '2024-05-19 20:10:52',
            ],
            [
                'id' => 8,
                'category_id' => 2,
                'vendor_id' => 3,
                'name' => 'Bưởi da xanh',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/662b5dccc7303.webp", "products/662b5dcd61475.webp", "products/662b5dcd896a8.webp"]',
                'unit' => 'kg',
                'quantity' => 6.30,
                'price' => 89000,
                'discount' => 0.22,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:54:53',
                'updated_at' => '2024-05-19 20:13:36',
            ],
            [
                'id' => 9,
                'category_id' => 2,
                'vendor_id' => 3,
                'name' => 'Cam sành',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/662b5f5ec3fdf.webp", "products/662b5f5ee34f3.webp", "products/662b5f5f183da.webp", "products/662b5f5f410c9.webp"]',
                'unit' => 'kg',
                'quantity' => 8.70,
                'price' => 27000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:56:14',
                'updated_at' => '2024-05-05 01:17:28',
            ],
            [
                'id' => 10,
                'category_id' => 1,
                'vendor_id' => 5,
                'name' => 'Cam vàng Ai Cập',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/662b5e6e81e2c.webp", "products/662b5e6f03220.webp", "products/662b5e6f2fc83.webp"]',
                'unit' => 'kg',
                'quantity' => 5.50,
                'price' => 99000,
                'discount' => 0.20,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:57:35',
                'updated_at' => '2024-05-17 23:48:13',
            ],
            [
                'id' => 11,
                'category_id' => 3,
                'vendor_id' => 4,
                'name' => 'Giỏ Trái Cây Tài Lộc - Phú Quý',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/662b5ed68ae7b.webp", "products/662b5ed6e99e3.webp", "products/662b5ed723576.webp"]',
                'unit' => 'giỏ',
                'quantity' => 1.00,
                'price' => 396000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 00:59:19',
                'updated_at' => '2024-05-19 01:33:27',
            ],
            [
                'id' => 12,
                'category_id' => 3,
                'vendor_id' => 4,
                'name' => 'Giỏ Trái Cây Nhập Tông Hồng Hoạ Tiết Vàng',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/662b5f1fc32e6.webp", "products/662b5f202b225.webp"]',
                'unit' => 'giỏ',
                'quantity' => 1.00,
                'price' => 700000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-04-26 01:00:32',
                'updated_at' => '2024-05-19 01:34:25',
            ],
            [
                'id' => 14,
                'category_id' => 1,
                'vendor_id' => 1,
                'name' => 'Dâu Hàn Quốc',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635f2dbd48ec.webp", "products/6635f2dcf0b12.webp", "products/6635f2ddd4dcb.webp"]',
                'unit' => 'kg',
                'quantity' => 7.90,
                'price' => 229000,
                'discount' => 0.15,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 01:33:34',
                'updated_at' => '2024-05-16 23:33:53',
            ],
            [
                'id' => 15,
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Quýt nội địa Trung',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635f66e91885.webp", "products/6635f66fc815b.webp", "products/6635f670c5909.webp"]',
                'unit' => 'kg',
                'weight' => 5.40,
                'price' => 89000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 01:48:49',
                'updated_at' => '2024-05-17 23:48:13',
            ],
            [
                'id' => 16,
                'category_id' => 2,
                'brand_id' => 3,
                'name' => 'Vải trứng Daklak có cành',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635f785583b4.webp"]',
                'unit' => 'kg',
                'weight' => 7.40,
                'price' => 129000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 01:53:25',
                'updated_at' => '2024-05-16 23:33:53',
            ],
            [
                'id' => 17,
                'category_id' => 2,
                'brand_id' => 3,
                'name' => 'Sầu riêng cơm Musang King Việt Nam',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635f84498575.webp"]',
                'unit' => 'kg',
                'weight' => 6.30,
                'price' => 318750,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 01:56:37',
                'updated_at' => '2024-05-18 17:05:22',
            ],
            [
                'id' => 18,
                'category_id' => 2,
                'brand_id' => 3,
                'name' => 'Mận xanh Tam Hoa',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635f8f1dc186.webp"]',
                'unit' => 'kg',
                'weight' => 7.60,
                'price' => 89000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 01:59:30',
                'updated_at' => '2024-05-17 23:51:15',
            ],
            [
                'id' => 19,
                'category_id' => 1,
                'brand_id' => 4,
                'name' => 'Nho đỏ Long Crimson Úc',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635f9abf06a9.webp", "products/6635f9ad041d2.webp", "products/6635f9adbc7c9.webp"]',
                'unit' => 'kg',
                'weight' => 8.90,
                'price' => 104500,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:02:38',
                'updated_at' => '2024-05-08 06:58:00',
            ],
            [
                'id' => 20,
                'category_id' => 2,
                'brand_id' => 5,
                'name' => 'Dưa lưới TL3',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fa4f10d65.webp"]',
                'unit' => 'kg',
                'weight' => 7.50,
                'price' => 210000,
                'discount' => 0.22,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:05:19',
                'updated_at' => '2024-05-17 23:51:15',
            ],
            [
                'id' => 21,
                'category_id' => 2,
                'brand_id' => 6,
                'name' => 'Ổi nữ hoàng',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fae80f329.webp"]',
                'unit' => 'kg',
                'weight' => 8.00,
                'price' => 45000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:07:52',
                'updated_at' => '2024-05-17 23:51:15',
            ],
            [
                'id' => 22,
                'category_id' => 2,
                'brand_id' => 6,
                'name' => 'Xoài cát hòa lộc',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fb2755e81.webp"]',
                'unit' => 'kg',
                'weight' => 5.50,
                'price' => 149000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:08:55',
                'updated_at' => '2024-05-18 17:05:12',
            ],
            [
                'id' => 23,
                'category_id' => 2,
                'brand_id' => 6,
                'name' => 'Bơ sáp',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fb78208e7.webp"]',
                'unit' => 'kg',
                'weight' => 8.20,
                'price' => 99000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:10:16',
                'updated_at' => '2024-05-17 23:51:15',
            ],
            [
                'id' => 24,
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Việt quất Mỹ',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fbd475224.webp", "products/6635fbd512f47.webp", "products/6635fbd5ec802.webp"]',
                'unit' => 'kg',
                'weight' => 9.70,
                'price' => 278000,
                'discount' => 0.20,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:11:50',
                'updated_at' => '2024-05-16 23:43:57',
            ],
            [
                'id' => 25,
                'category_id' => 2,
                'brand_id' => 6,
                'name' => 'Dưa hấu đỏ không hạt',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fc2e9a3fe.webp"]',
                'unit' => 'kg',
                'weight' => 3.90,
                'price' => 156000,
                'discount' => 0.12,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:13:19',
                'updated_at' => '2024-05-18 17:05:22',
            ],
            [
                'id' => 26,
                'category_id' => 2,
                'brand_id' => 4,
                'name' => 'Đu đủ',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fc6b710d2.webp"]',
                'unit' => 'kg',
                'weight' => 10.00,
                'price' => 43500,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:14:20',
                'updated_at' => '2024-05-05 00:51:47',
            ],
            [
                'id' => 27,
                'category_id' => 2,
                'brand_id' => 4,
                'name' => 'Mận đỏ An Phước',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fcb2f2fde.webp", "products/6635fcb386101.webp", "products/6635fcb3d0b80.webp"]',
                'unit' => 'kg',
                'weight' => 8.80,
                'price' => 78000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:15:31',
                'updated_at' => '2024-05-16 23:45:54',
            ],
            [
                'id' => 28,
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Măng cụt Thái Lan',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fd07baef9.webp", "products/6635fd0937f28.webp", "products/6635fd0a0b906.webp"]',
                'unit' => 'kg',
                'weight' => 8.50,
                'price' => 59500,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:16:58',
                'updated_at' => '2024-05-18 16:53:10',
            ],
            [
                'id' => 29,
                'category_id' => 2,
                'brand_id' => 5,
                'name' => 'Chuối Dole 3 trái',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fd41a4887.webp"]',
                'unit' => 'kg',
                'weight' => 5.40,
                'price' => 29000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:17:54',
                'updated_at' => '2024-05-17 23:46:48',
            ],
            [
                'id' => 30,
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Lựu đỏ Peru',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fda8d2cf7.webp", "products/6635fdaa22ecf.webp", "products/6635fdab0eb14.webp"]',
                'unit' => 'kg',
                'weight' => 8.30,
                'price' => 254250,
                'discount' => 0.18,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:19:39',
                'updated_at' => '2024-05-18 16:56:37',
            ],
            [
                'id' => 31,
                'category_id' => 2,
                'brand_id' => 6,
                'name' => 'Thanh long ruột đỏ',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fdf98c07f.webp"]',
                'unit' => 'kg',
                'weight' => 8.60,
                'price' => 89000,
                'discount' => 0.20,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:20:58',
                'updated_at' => '2024-05-17 23:46:48',
            ],
            [
                'id' => 32,
                'category_id' => 2,
                'brand_id' => 4,
                'name' => 'Bưởi đường lá cam Tân Triều',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635fe4f21b59.webp", "products/6635fe4f9078f.webp", "products/6635fe4fc0464.webp"]',
                'unit' => 'kg',
                'weight' => 5.50,
                'price' => 37000,
                'discount' => 0.00,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:22:23',
                'updated_at' => '2024-05-18 16:56:37',
            ],
            [
                'id' => 33,
                'category_id' => 2,
                'brand_id' => 3,
                'name' => 'Đu đủ ruột đỏ giống Đài Loan',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635feda90e24.webp"]',
                'unit' => 'kg',
                'weight' => 8.60,
                'price' => 45000,
                'discount' => 0.25,
                'status' => 'Còn hàng',
                'created_at' => '2024-05-04 02:24:08',
                'updated_at' => '2024-05-18 00:57:58',
            ],
            [
                'id' => 34,
                'category_id' => 3,
                'brand_id' => 5,
                'name' => 'Giỏ Trái Cây Nhập Healthy Living',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635ff55d1307.webp", "products/6635ff5657cba.webp"]',
                'unit' => 'giỏ',
                'weight' => 0.00,
                'price' => 1200000,
                'discount' => 0.00,
                'status' => 'Tạm hết hàng',
                'created_at' => '2024-05-04 02:26:46',
                'updated_at' => '2024-05-05 00:56:19',
            ],
            [
                'id' => 35,
                'category_id' => 3,
                'brand_id' => 5,
                'name' => 'Hộp Quà Trái Cây Nhập Màu Hồng Hoạ Tiết Vàng',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6635ffd29730b.webp"]',
                'unit' => 'giỏ',
                'weight' => 0.00,
                'price' => 1100000,
                'discount' => 0.00,
                'status' => 'Tạm hết hàng',
                'created_at' => '2024-05-04 02:28:51',
                'updated_at' => '2024-05-05 00:56:19',
            ],
            [
                'id' => 36,
                'category_id' => 3,
                'brand_id' => 5,
                'name' => 'Giỏ Trái Cây Nhập Lục Bình',
                'description' => "Trái cây tươi ngon",
                'images' => '["products/6636000aedafc.webp", "products/6636000b55512.webp"]',
                'unit' => 'giỏ',
                'weight' => 0.00,
                'price' => 1700000,
                'discount' => 0.00,
                'status' => 'Tạm hết hàng',
                'created_at' => '2024-05-04 02:29:47',
                'updated_at' => '2024-05-05 00:56:19',
            ],
        ]);
    }
}
