<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Việt Hoàng',
                'email' => 'hong@gmail.com',
                'user_type' => 1,
                'phone' => '112121212',
                'address' => 'Lien Trung, Dan Phuong, Ha Noi',
                'password' => bcrypt('hoangviet12'),
                'profile_photo_path' => 'users/66485fc2ab197.jpg',
                'status' => 'active',
                'created_at' => '2024-04-25 03:18:54',
                'updated_at' => '2024-05-18 00:58:59',
            ],
            [
                'id' => 3,
                'name' => 'Hoàng Việt',
                'email' => 'noneedforlife.0612@gmail.com',
                'user_type' => 0,
                'phone' => '038847594',
                'address' => 'Liên Trung, Đan Phượng, Hà Nội',
                'password' => bcrypt('hoangviet12'),
                'profile_photo_path' => 'users/6639a0fec9d9c.jpg',
                'status' => 'active',
                'created_at' => '2024-05-03 01:08:04',
                'updated_at' => '2024-05-06 20:33:19',
            ],
            [
                'id' => 4,
                'name' => 'Nguyễn Hông Hạnh',
                'email' => 'nguyenhonghanh@gmail.com',
                'user_type' => 0,
                'phone' => '0395487555',
                'address' => 'Số 10, Ngõ 45, Lê Văn, Thanh Xuân, Hà Nội',
                'password' => bcrypt('hoangviet12'),
                'profile_photo_path' => 'users/66359ccd09bf4.jpg',
                'status' => 'active',
                'created_at' => '2024-05-03 19:25:51',
                'updated_at' => '2024-05-03 19:26:21',
            ],
            [
                'id' => 5,
                'name' => 'Kỳ Duyên',
                'email' => 'kyduyen@gmail.com',
                'user_type' => 0,
                'phone' => '0987654321',
                'address' => 'Tầng 3, Tòa nhà TNR, Đường Lê Văn Lương, Thanh Xuân, Hà Nội',
                'password' => bcrypt('hoangviet12'),
                'profile_photo_path' => 'users/66359d398a422.jpg',
                'status' => 'active',
                'created_at' => '2024-05-03 19:27:44',
                'updated_at' => '2024-05-03 19:28:09',
            ],
            [
                'id' => 6,
                'name' => 'Lan Hương',
                'email' => 'lanhuong@gmail.com',
                'user_type' => 0,
                'phone' => '09866554433',
                'address' => 'Số 15, Ngõ 32, Cầu Giấy, Hà Nội',
                'password' => bcrypt('hoangviet12'),
                'profile_photo_path' => 'users/66359d85a000f.jpg',
                'status' => 'active',
                'created_at' => '2024-05-03 19:29:07',
                'updated_at' => '2024-05-03 19:29:25',
            ],
            [
                'id' => 7,
                'name' => 'Phan Thanh Hưng',
                'email' => 'phanthanhhung@gmail.com',
                'user_type' => 0,
                'phone' => '094455667',
                'address' => 'Số 12, Phố Xuân Diệu, Tây Hồ, Hà Nội',
                'password' => bcrypt('hoangviet12'),
                'profile_photo_path' => 'users/66359e970f20f.jpg',
                'status' => 'active',
                'created_at' => '2024-05-03 19:33:42',
                'updated_at' => '2024-05-03 19:33:59',
            ],
            [
                'id' => 8,
                'name' => 'Nguyễn Đức Hải',
                'email' => 'nguyenduchai@gmail.com',
                'user_type' => 0,
                'phone' => '09999999',
                'address' => 'Số 20, Phố Hàng Điếu, Hoàn Kiếm, Hà Nội',
                'password' => bcrypt('hoangviet12'),
                'profile_photo_path' => 'users/66359f73adf8b.jpg',
                'status' => 'deactive',
                'created_at' => '2024-05-03 19:37:24',
                'updated_at' => '2024-05-04 00:35:54',
            ],
            [
                'id' => 9,
                'name' => 'Nguyễn Ngọc Linh',
                'email' => 'ngoclinh22@gmail.com',
                'user_type' => 0,
                'phone' => '038899776',
                'address' => 'Số 10, Ngõ 45, Lê Văn Lương, Thanh Xuân, Hà Nộii',
                'password' => bcrypt('hoangviet12'),
                'profile_photo_path' => 'users/66359fd173cee.jpg',
                'status' => 'active',
                'created_at' => '2024-05-03 19:38:56',
                'updated_at' => '2024-05-03 19:39:13',
            ],
            [
                'id' => 10,
                'name' => 'Hoàng Huyền Hoa',
                'email' => 'huyenhoa99@gmail.com',
                'user_type' => 0,
                'phone' => '0998833445',
                'address' => '35b Ngh. 76/2 Vĩnh Hưng, Vĩnh Hưng, Hoàng Mai, Hà Nội, Việt Nam',
                'password' => bcrypt('hoangviet12'),
                'profile_photo_path' => 'users/6635a07b198f7.jpg',
                'status' => 'active',
                'created_at' => '2024-05-03 19:41:48',
                'updated_at' => '2024-05-03 19:42:03',
            ],
            [
                'id' => 11,
                'name' => 'Đoàn Trâm Anh',
                'email' => 'tramanh99@gmail.com',
                'user_type' => 0,
                'phone' => '037766889',
                'address' => 'Đường P. Dương Văn Bé, P, Hai Bà Trưng, Hà Nội, Việt Nam',
                'password' => bcrypt('hoangviet12'),
                'profile_photo_path' => 'users/6635a0dcb50aa.jpg',
                'status' => 'active',
                'created_at' => '2024-05-03 19:41:48',
                'updated_at' => '2024-05-03 19:42:03',
            ],
            [
                'id' => 12,
                'name' => 'Lưu Mỹ Kiều',
                'email' => 'luukieu123@gmail.com',
                'user_type' => 0,
                'phone' => '034987654',
                'address' => '3Q2R+HX8, Unnamed Road, Cổ Nhuế, Bắc Từ Liêm, Hà Nội, Việt Nam',
                'password' => bcrypt('hoangviet12'),
                'profile_photo_path' => 'users/6635a1e09ebff.jpg',
                'status' => 'active',
                'created_at' => '2024-05-03 19:47:46',
                'updated_at' => '2024-05-03 19:48:00',
            ],
            [
                'id' => 13,
                'name' => 'Nguyễn Văn Tuấn',
                'email' => 'nguyentuan2k2@gmail.com',
                'user_type' => 0,
                'phone' => '098345675',
                'address' => 'B6 Vinhome Gardenia, P. Hàm Nghi, Cầu Diễn, Từ Liêm, Hà Nội, Việt Nam',
                'password' => bcrypt('hoangviet12'),
                'profile_photo_path' => 'users/6635a23b047df.jpg',
                'status' => 'active',
                'created_at' => '2024-05-03 19:49:17',
                'updated_at' => '2024-05-03 19:49:31',
            ],
        ]);
    }
}
